// Generated by CoffeeScript 1.2.1-pre
var giles;

giles = require('../giles');

describe('watch', function() {
  return it('should assert', function() {
    return [1, 2, 3].indexOf(5).should.equal(-1);
  });
});

describe('giles', function() {
  return it('should get extensions', function() {
    giles.parseFileName('test.test').should.eql(['test', '.test']);
    giles.parseFileName('test').should.eql(['test', '']);
    giles.parseFileName('.test').should.eql(['', '.test']);
    giles.parseFileName('file.min.css').should.eql(['file.min', '.css']);
    return giles.parseFileName('file.really.long-whatever-name.out').should.eql(['file.really.long-whatever-name', '.out']);
  });
});

describe('new compiler', function() {
  return it('should compile correctly', function() {
    var result;
    giles.addCompiler('.test-giles-compiler', '.test-giles-compiler-out', function(contents) {
      return contents.substr(0, 5);
    });
    result = giles.compileFile(__dirname + '/test.test-giles-compiler');
    result.content.should.equal(result.originalContent.substr(0, 5));
    result.outputFile.indexOf('test.test-giles-compiler-out').should.not.eql(-1);
    return result.inputFile.indexOf('test.test-giles-compiler').should.not.eql(-1);
  });
});
